blank_issues_enabled: true
contact_links:
  - name: Keep The Why Discussions
    url: https://github.com/oliver-zehentleitner/keep-the-why/discussions
    about: Ask general questions.
  - name: Keep The Why docs
    url: https://keepthewhy.com/
    about: The complete UNICORN Binance WebSocket API documentation.
  - name: UNICORN Devs Chat
    url: https://t.me/unicorndevs
    about: Chat with the community about Keep The Why and ask general questions.